name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-prod

      # - name: Run tests
      #   run: npm run test-ci

      - name: Run Lint
        run: npm run lint

      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Zip
      #   run: zip release.zip ./* -r

      # - name: Upload
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-app
      #     path: release.zip

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "cicdexampleleroux"
          package: ./dist/cicdexample
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
